name: SoCalGas Usage Importer
version: "1.5"
slug: socalgas_usage
description: Import SoCalGas usage into Home Assistant
startup: services
boot: auto

map:
  - share:rw

arch:
  - amd64
  - aarch64

options:
  email: ""
  password: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic: "home/socalgas/total"
  update_interval_hours: 6
  debug: false

schema:
  email: str
  password: password
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_topic: str?
  update_interval_hours: int(1,24)?
  debug: bool

